packages:
  - 'packages/*'
  - 'apps/*'
overrides:
  react: 19.3.0-canary-68631c04-20260626
  react-dom: 19.3.0-canary-68631c04-20260626
allowBuilds:
  esbuild: true
  lefthook: true
minimumReleaseAgeExclude:
  - '@playwright/test@1.62.0-alpha-2026-06-28'
  - playwright-core@1.62.0-alpha-2026-06-28
  - playwright@1.62.0-alpha-2026-06-28
