// Stub type declarations for the WASM build output.
// The actual .js/.wasm files are generated by `wasm-pack build` (run `pnpm build:wasm`).
// This file allows TypeScript to type-check the package without running the Rust build.

export class WasmSearchEngine {
  index_items(serialized_json: string): void;
  search(
    query: string,
    max_results: number,
  ): Array<{ id: string; score: number; matches: Array<[number, number]> }>;
  clear(): void;
  free(): void;
}
