name: Docs
on:
  push:
    branches: [main]
    paths: ['apps/docs/**', 'packages/*/src/**']

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '25.8.0'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm docs:build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: apps/docs/.vitepress/dist
      - id: deployment
        uses: actions/deploy-pages@v4
